stages:
  - build
  - deploy
  
build:
  stage: build
  tags: ['armincall']
  only:
    - master
  script:
    - npm install
    
deploy:
  stage: deploy
  tags: ['armincall']
  only:
    - master
  variables:
    GIT_STRATEGY: none
  script:
     - forever stopall && forever start server.js
    
