stages:
  - build
  - deploy
  
install_node_dependencies:
  stage: build
  tags: ['armincall']
  script:
    - npm install

compile_ng2:
  stage: build
  tags: ['armincall']
  script:
    - cd ./client && ng build --prod
  
deploy:
  stage: deploy
  tags: ['armincall']
  script:
     - forever stopall && forever start server.js
    
